// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz36G4_Xgm3D2ApDWou7w-GKV9PYByego',
    appId: '1:422090467811:web:fd12ec1865da4729b498d6',
    messagingSenderId: '422090467811',
    projectId: 'time-counter-74a49',
    authDomain: 'time-counter-74a49.firebaseapp.com',
    databaseURL: 'https://time-counter-74a49-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'time-counter-74a49.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu7wHlZjnTLbd3Id7T8VLvxLnDD91Dw90',
    appId: '1:422090467811:android:5ca626f54a37e5c1b498d6',
    messagingSenderId: '422090467811',
    projectId: 'time-counter-74a49',
    databaseURL: 'https://time-counter-74a49-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'time-counter-74a49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPpvZ-PaHjqi7bXCsMWgNyM1Cx09wcfdU',
    appId: '1:422090467811:ios:93ebc4c677016c22b498d6',
    messagingSenderId: '422090467811',
    projectId: 'time-counter-74a49',
    databaseURL: 'https://time-counter-74a49-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'time-counter-74a49.appspot.com',
    androidClientId: '422090467811-m5qfg8jq5e4dpdo3mo0g6lbbs6i58tup.apps.googleusercontent.com',
    iosClientId: '422090467811-mg9kknj4mkml8c63bv6ksjajus9b335r.apps.googleusercontent.com',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPpvZ-PaHjqi7bXCsMWgNyM1Cx09wcfdU',
    appId: '1:422090467811:ios:6ffb9398a8944383b498d6',
    messagingSenderId: '422090467811',
    projectId: 'time-counter-74a49',
    databaseURL: 'https://time-counter-74a49-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'time-counter-74a49.appspot.com',
    androidClientId: '422090467811-m5qfg8jq5e4dpdo3mo0g6lbbs6i58tup.apps.googleusercontent.com',
    iosClientId: '422090467811-32ao350p51shlupto1g2r7pctb149b1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.testing.RunnerTests',
  );
}
